
[general]
	music_service = "spotify"
	link_mode = 1
	announce_new_song = 0
	announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"
	notification_album_art_location = 1
	first_time = false
	mod_mode = -1

[servers]
	send_songs_to_servers = false
	allowed_servers = ""

[rendering]
	anchor_point = 1
	position_x_offset = 0.0
	position_y_offset = 0.0
	render_type = 2
	display_mode = 2
	controls = false

[login]
	service_port = 8880
	spotify_login_token = "BQABhbcl8MKxqCrQ-Nta8wXfX8jEEd-IwWiP9RnUVO0ZiPjbOf7hsaKbpzX2dO4MggTQgYr-BX1KFvXzFU-cnvaTz3uXWbSGgey3nByNRbqk0LSClcZwwL6hLKFnFw3iO1gT8-xVWPSDw17MU4C6b-HTKOyluJHATw8hWw6XpG8sih-phmBF545IJQkTWkEwgMqk2gYUeFs"
	refresh_token = "AQBUQJ_vnjbZNydrOiKOL1g-FlmZrD1lDEs1ZInbFwA7ml1pG34TcKvudHTIRlzQKzKJ5ISWzyibfsrKBOpJmWzGBSxrCzcqqb2kQ_wu5mssQB4LPLY6YV1Vc_jc7ZuRHL0"
	ytmd_token = ""

